INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Marcel Marreti Rosa', 'marcel.rosa@assistenciacompany.com.br',991539398);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Natan Novak', 'natan.novak@assistenciacompany.com.br', 983317859);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Karen Moreno Spisso', 'karen.spisso@assistenciacompany.com.br', 987342722);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Juliana Gomes Proenca', 'juliana.proenca@assistenciacompany.com.br', 985161133);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Geovanna Carolina Favilla', 'geovanna.favilla@assistenciacompany.com.br', 989181174);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Douglas Quintiliano Calixto', 'douglas.calixto@assistenciacompany.com.br', 997254303);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Bruno Pavanelli Couto', 'bruno.couto@assistenciacompany.com.br', 984666718);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Amanda Gaeta Parigini', 'amanda.parigini@assistenciacompany.com.br', 973802424);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Adnam Marques Batista Junior', 'adnam.junior@assistenciacompany.com.br', 983214823);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Alexandre Claret Albertos', 'alexandre.albertos@assistenciacompany.com.br', 982179402);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Frederico Ribeiro Vilela Santeiro', 'frederico.santeiro@assistenciacompany.com.br', 972275110);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Gabriel Biscaro Cavallari', 'gabriel.cavallari@assistenciacompany.com.br', 973385848);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Gabriel Ferreira Monteiro', 'gabriel.monteiro@assistenciacompany.com.br', 994841155);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Giorgia Soares Agostini', 'giorgia.agostini@assistenciacompany.com.br', 992148383);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Lais Manesco Grigolon', 'lais.grigolon@assistenciacompany.com.br', 976318635);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Leticia Consoline', 'leticia.consoline@assistenciacompany.com.br', 995142638);
INSERT INTO TBL_TECNICO(TX_NOME, TX_EMAIL, TX_FONE) VALUES ('Lucas Alexandre Soares', 'lucas.soares@assistenciacompany.com.br', 973898164);
